I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/draggables.rpy", line 1, in script
    init python:
  File "game/draggables.rpy", line 1, in script
    init python:
  File "game/draggables.rpy", line 2, in <module>
    from enum import Enum
ImportError: No module named enum

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "renpy/bootstrap.py", line 326, in bootstrap
    renpy.main.main()
  File "renpy/main.py", line 515, in main
    renpy.game.context().run(node)
  File "game/draggables.rpy", line 1, in script
    init python:
  File "game/draggables.rpy", line 1, in script
    init python:
  File "renpy/ast.py", line 922, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "renpy/python.py", line 2218, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/draggables.rpy", line 2, in <module>
    from enum import Enum
ImportError: No module named enum

Windows-10-10.0.19041
Ren'Py 7.4.5.1648
powerplant 1.0
Sat May 29 20:07:08 2021
